// <auto-generated />
using GrimorioDigital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrimorioDigital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512121459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GrimorioDigital.Models.EscolaDeMagia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EscolasDeMagia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Magias de invocação de elementos",
                            Elemento = "Fogo",
                            Nome = "Evocação"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Magias relacionadas à morte e não-mortos",
                            Elemento = "Sombra",
                            Nome = "Necromancia"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Magias de engano e ilusão",
                            Elemento = "Arcano",
                            Nome = "Ilusão"
                        });
                });

            modelBuilder.Entity("GrimorioDigital.Models.Feiticeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscolaDeMagiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EscolaDeMagiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Feiticeiros");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Raiz mágica rara",
                            Nome = "Raiz de Mandragora",
                            Quantidade = 10,
                            Raridade = "Raro"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Resíduo de dragão ancião",
                            Nome = "Pó de Osso de Dragão",
                            Quantidade = 3,
                            Raridade = "Lendario"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Erva comum com propriedades sedativas",
                            Nome = "Erva do Sono",
                            Quantidade = 50,
                            Raridade = "Comum"
                        });
                });

            modelBuilder.Entity("GrimorioDigital.Models.Magia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscolaDeMagiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAlvo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EscolaDeMagiaId");

                    b.ToTable("Magias");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Pocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Efeito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pocoes");
                });

            modelBuilder.Entity("GrimorioDigital.Models.PocaoIngrediente", b =>
                {
                    b.Property<int>("PocaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeNecessaria")
                        .HasColumnType("INTEGER");

                    b.HasKey("PocaoId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("PocaoIngredientes");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Feiticeiro", b =>
                {
                    b.HasOne("GrimorioDigital.Models.EscolaDeMagia", "EscolaDeMagia")
                        .WithMany("Feiticeiros")
                        .HasForeignKey("EscolaDeMagiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GrimorioDigital.Models.Usuario", "Usuario")
                        .WithMany("Feiticeiros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscolaDeMagia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Magia", b =>
                {
                    b.HasOne("GrimorioDigital.Models.EscolaDeMagia", "EscolaDeMagia")
                        .WithMany("Magias")
                        .HasForeignKey("EscolaDeMagiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EscolaDeMagia");
                });

            modelBuilder.Entity("GrimorioDigital.Models.PocaoIngrediente", b =>
                {
                    b.HasOne("GrimorioDigital.Models.Ingrediente", "Ingrediente")
                        .WithMany("PocaoIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrimorioDigital.Models.Pocao", "Pocao")
                        .WithMany("PocaoIngredientes")
                        .HasForeignKey("PocaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Pocao");
                });

            modelBuilder.Entity("GrimorioDigital.Models.EscolaDeMagia", b =>
                {
                    b.Navigation("Feiticeiros");

                    b.Navigation("Magias");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Ingrediente", b =>
                {
                    b.Navigation("PocaoIngredientes");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Pocao", b =>
                {
                    b.Navigation("PocaoIngredientes");
                });

            modelBuilder.Entity("GrimorioDigital.Models.Usuario", b =>
                {
                    b.Navigation("Feiticeiros");
                });
#pragma warning restore 612, 618
        }
    }
}
